export type DecisionCaseDiagnosticCode =
  | "DECISION_CASE_INVALID"
  | "DECISION_CASE_UNSUPPORTED_SEMANTICS"
  | "DECISION_CASE_UNSUPPORTED_OPERATION"
  | "DECISION_CASE_EVIDENCE_SOURCE_MISMATCH"
  | "DECISION_CASE_EVIDENCE_SPAN_MISMATCH"
  | "DECISION_CASE_MODEL_INPUT_UNDECLARED"
  | "DECISION_CASE_DEPENDENCY_INVALID"
  | "DECISION_CASE_DEPENDENCY_CYCLE"
  | "DECISION_CASE_ANALYSIS_NOT_FOUND"
  | "DECISION_CASE_STALE_SUBJECT_BINDING"
  | "DECISION_CASE_ENGINE_UNAVAILABLE"
  | "DECISION_CASE_ENGINE_PIN_MISMATCH"
  | "DECISION_CASE_ENGINE_PROTOCOL_ERROR"
  | "DECISION_CASE_MATHEMATICAL_CHECK_FAILED"
  | "DECISION_CASE_APPLICABILITY_REASSESSMENT_REQUIRED"
  | "DECISION_CASE_UNSUPPORTED_USE"
  | "DECISION_CASE_OUTPUT_EXISTS";

export class DecisionCaseError extends Error {
  constructor(
    readonly code: DecisionCaseDiagnosticCode,
    message: string,
    readonly detail?: Readonly<Record<string, unknown>>,
  ) {
    super(message);
    this.name = "DecisionCaseError";
  }
}
