/**
 * Generate the small, typed corpus projection used by the homepage corpus field.
 *
 * `corpora/catalog.yaml` remains the authority for native corpus identity. Each
 * catalog entry is reconciled with its referenced manifest so presentation can
 * use the real title, family, jurisdiction, status, and instrument/institution
 * identity without teaching the browser how to read the repository.
 *
 * The projection is deterministic: local files only, no clock, network, or
 * randomness. Retired migration entries are deliberately excluded.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  catalogPath,
  issuerLabel,
  nonNegativeInteger,
  readNativeCorpora,
  repoRoot,
  stringList,
  text,
} from "./lib/read-native-corpora";

const FEATURED_CORPUS_IDS = new Set([
  "writ.corpus.legal-policy.eu.european-union.artificial-intelligence-act-2024-1689",
  "writ.corpus.legal-policy.eu.european-commission.gpai-guidelines",
  "writ.corpus.legal-policy.eu.european-commission.gpai-code-of-practice-signatory-notice",
  "writ.corpus.legal-policy.us.nist.ai-risk-management-framework-1-0",
  "writ.corpus.legal-policy.us.nist.generative-ai-profile",
  "writ.corpus.legal-policy.us.office-of-management-and-budget.m-25-21",
  "writ.corpus.legal-policy.us.white-house.americas-ai-action-plan",
  "eu.institutions.european_commission",
  "us.institutions.nist",
]);

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, "..", "lib", "corpus-catalog-data.ts");
const nativeCorpora = readNativeCorpora();
const projection = nativeCorpora.map((corpus) => {
  const { entry, manifest: record, manifestText } = corpus;

  const mappedCountKind = record.family === "legal_policy" ? "claims" : "institutional_records";
  const mappedCountValue = record.record_counts[mappedCountKind];
  const mappedCount =
    mappedCountValue === undefined && record.family === "legal_policy"
      ? 0
      : nonNegativeInteger(mappedCountValue, `${entry.manifest}.record_counts.${mappedCountKind}`);
  const sources = stringList(record.locations.sources, `${entry.manifest}.locations.sources`);
  const records = stringList(record.locations.records, `${entry.manifest}.locations.records`);
  if (records.length === 0) throw new TypeError(`${entry.manifest}.locations.records is empty`);

  const rawFiles = FEATURED_CORPUS_IDS.has(entry.corpus_id)
    ? (() => {
        const primaryRecord = text(records.at(-1), `${entry.manifest}.locations.records[-1]`);
        const primaryRecordPath = join(entry.path, primaryRecord);
        const extension = extname(primaryRecord).slice(1);
        return [
          {
            name: "corpus.yaml",
            language: "yaml" as const,
            path: entry.manifest,
            content: manifestText,
          },
          {
            name: basename(primaryRecord),
            language: extension === "writ" ? ("writ" as const) : ("yaml" as const),
            path: primaryRecordPath,
            content: readFileSync(join(repoRoot, primaryRecordPath), "utf8"),
          },
        ];
      })()
    : undefined;

  return {
    corpusId: entry.corpus_id,
    family: entry.family,
    jurisdiction: entry.jurisdiction,
    status: entry.status,
    title: record.title,
    issuer: issuerLabel(corpus),
    identity: record.instrument_id ?? record.root_institution_id ?? entry.corpus_id,
    path: entry.path,
    mappedCount,
    mappedCountKind,
    sourceFileCount: sources.length,
    unresolvedEvidenceCount: record.unresolved_evidence_count,
    ...(rawFiles ? { rawFiles } : {}),
  };
});

const body = `// AUTO-GENERATED by apps/web/scripts/embed-corpus-catalog.ts — do not edit by hand.
// Source: corpora/catalog.yaml and the native corpus manifests it references.

export type CatalogCorpusFamily = "legal_policy" | "institutional";
export type CatalogCorpusStatus = "active" | "draft";

export interface CatalogCorpusSummary {
  readonly corpusId: string;
  readonly family: CatalogCorpusFamily;
  readonly jurisdiction: string;
  readonly status: CatalogCorpusStatus;
  readonly title: string;
  readonly issuer: string;
  readonly identity: string;
  readonly path: string;
  readonly mappedCount: number;
  readonly mappedCountKind: "claims" | "institutional_records";
  readonly sourceFileCount: number;
  readonly unresolvedEvidenceCount: number;
  readonly rawFiles?: readonly CatalogRawFile[];
}

export interface CatalogRawFile {
  readonly name: string;
  readonly language: "yaml" | "writ";
  readonly path: string;
  readonly content: string;
}

export const CORPUS_CATALOG_SOURCE = ${JSON.stringify(catalogPath)};
// prettier-ignore
export const CORPUS_CATALOG: readonly CatalogCorpusSummary[] = Object.freeze(${JSON.stringify(projection, null, 2)});
`;

writeFileSync(outFile, body);
console.log(`embed-corpus-catalog: wrote ${outFile} (${projection.length} native corpora)`);
