/**
 * Generate `lib/frozen-data.ts` — the frozen repo data the server layer reads
 * (the pilot methodologies, its evidence snapshots, its interpretation profile,
 * and its provenance) inlined as text, keyed by repo-relative path, so it can be
 * served without a runtime filesystem read.
 *
 * Why: on Vercel the serverless lambda root is `/var/task`, and none of the
 * repo data dirs are shipped there (outputFileTracingIncludes for parent-of-app
 * files is not honored, and the packages bake a build-time `import.meta.url`
 * path). Inlining the exact files `lib/toolchain.ts` reads removes that fragility.
 * The data is frozen; `prebuild` regenerates this file so it can never drift.
 *
 * Run: `bun scripts/embed-frozen.ts` (wired as the web app `prebuild`).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const outFile = join(here, "..", "lib", "frozen-data.ts");

const PILOT = "pilot/eu-us-ai-evaluation";

// Exactly the files the server layer reads at runtime.
const rels: string[] = [
  // Provenance for the reviewed EU-US pilot: which document each row came
  // from, when it was retrieved, its byte hash, and the verbatim passage.
  `${PILOT}/provenance/document-versions.json`,
  `${PILOT}/provenance/passages.json`,
  `${PILOT}/provenance/unresolved.json`,
  // The Lab runs these: four readings of the same question, the evidence
  // snapshots they run against, and the profile they run under.
  `${PILOT}/methodology/model-evaluation-duty.writ`,
  `${PILOT}/methodology/any-actor-any-force.writ`,
  `${PILOT}/methodology/broad-conduct.writ`,
  `${PILOT}/methodology/incomplete-score.writ`,
  `${PILOT}/evidence/eu.snapshot.json`,
  `${PILOT}/evidence/us.snapshot.json`,
  `${PILOT}/evidence/coverage.json`,
  `${PILOT}/profiles/reviewed.profile.json`,
];

const entries = rels
  .map((rel) => {
    const text = readFileSync(join(repoRoot, rel), "utf8");
    return `  ${JSON.stringify(rel)}: ${JSON.stringify(text)},`;
  })
  .join("\n");

const body = `// AUTO-GENERATED by scripts/embed-frozen.ts — do not edit by hand.
// The frozen example sources, the 2025 AI-for-SMEs benchmark corpus, and the
// normalized G20 2024 Rio compliance corpus, inlined as text keyed by
// repo-relative path, so the server layer loads them without a filesystem read
// (safe on Vercel, where the repo data is not shipped to the lambda).
// Regenerated by \`prebuild\`.

export const FROZEN_FILES: Readonly<Record<string, string>> = Object.freeze({
${entries}
});
`;

writeFileSync(outFile, body);
console.log(`embed-frozen: wrote ${outFile} (${rels.length} files)`);
