/**
 * Generate `lib/frozen-data.ts` — the frozen repo data (example sources + the
 * 2025 AI-for-SMEs benchmark corpus) inlined as text, keyed by repo-relative
 * path, so the server layer can serve it without a runtime filesystem read.
 *
 * Why: on Vercel the serverless lambda root is `/var/task`, and none of the
 * repo data dirs are shipped there (outputFileTracingIncludes for parent-of-app
 * files is not honored, and the packages bake a build-time `import.meta.url`
 * path). Inlining the exact files `lib/toolchain.ts` reads removes that fragility.
 * The data is frozen; `prebuild` regenerates this file so it can never drift.
 *
 * Run: `bun scripts/embed-frozen.ts` (wired as the web app `prebuild`).
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const outFile = join(here, "..", "lib", "frozen-data.ts");

const BENCH = "benchmark/2025-ai-sme";

// Exactly the files the server layer (lib/toolchain.ts) reads at runtime.
const rels: string[] = [
  "examples/2025-ai-sme-literal.covenant",
  "examples/2025-ai-sme-resolved.covenant",
  "examples/2025-ai-sme-inclusive-up-to.covenant",
  "examples/ai-governance-gap-matrix.covenant",
  "benchmark/ai-governance-gap-matrix/assessments.json",
  `${BENCH}/discrepancy-ledger.json`,
  ...readdirSync(join(repoRoot, BENCH, "evidence"))
    .filter((f) => f.endsWith(".snapshot.json"))
    .sort()
    .map((f) => `${BENCH}/evidence/${f}`),
  ...readdirSync(join(repoRoot, BENCH, "profiles"))
    .filter((f) => f.endsWith(".json"))
    .sort()
    .map((f) => `${BENCH}/profiles/${f}`),
];

const entries = rels
  .map((rel) => {
    const text = readFileSync(join(repoRoot, rel), "utf8");
    return `  ${JSON.stringify(rel)}: ${JSON.stringify(text)},`;
  })
  .join("\n");

const body = `// AUTO-GENERATED by scripts/embed-frozen.ts — do not edit by hand.
// The frozen example sources and 2025 AI-for-SMEs benchmark corpus, inlined as
// text keyed by repo-relative path, so the server layer loads them without a
// filesystem read (safe on Vercel, where the repo data is not shipped to the
// lambda). Regenerated by \`prebuild\`.

export const FROZEN_FILES: Readonly<Record<string, string>> = Object.freeze({
${entries}
});
`;

writeFileSync(outFile, body);
console.log(`embed-frozen: wrote ${outFile} (${rels.length} files)`);
