/**
 * Generate `lib/repo-provenance.ts` — the repository facts a downloaded memo
 * carries so a reader can trace it back: the canonical remote, the commit the
 * memo was generated from, and what the repository actually says about rights.
 *
 * Everything here is read from the repository. Nothing is supplied by hand.
 * In particular, if there is no LICENSE file and no copyright notice, that is
 * what gets recorded — a memo must not imply terms the repository never granted.
 *
 * Why a build step: on Vercel the lambda has no `.git`, so the commit has to be
 * resolved while the repository is still present. `VERCEL_GIT_COMMIT_SHA` is
 * used when git is unavailable.
 *
 * Run: `bun scripts/embed-provenance.ts` (wired as part of the web app build).
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const outFile = join(here, "..", "lib", "repo-provenance.ts");

function git(...args: string[]): string | undefined {
  try {
    return execFileSync("git", args, { cwd: repoRoot, encoding: "utf8" }).trim() || undefined;
  } catch {
    return undefined;
  }
}

const commit = git("rev-parse", "HEAD") ?? process.env.VERCEL_GIT_COMMIT_SHA;

/** The canonical remote as a browsable https URL, with any credentials dropped. */
function canonicalRemote(): string | undefined {
  const raw = git("remote", "get-url", "origin");
  if (!raw) return undefined;
  const ssh = raw.match(/^git@([^:]+):(.+?)(?:\.git)?$/);
  if (ssh) return `https://${ssh[1]}/${ssh[2]}`;
  try {
    const url = new URL(raw);
    url.username = "";
    url.password = "";
    return url.toString().replace(/\.git$/, "");
  } catch {
    return undefined;
  }
}

/** Candidate licence files, in the order a reader would look for them. */
const LICENCE_FILES = ["LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING", "COPYING.md"];
const DATA_LICENCE_FILES = [
  "pilot/eu-us-ai-evaluation/LICENSE",
  "pilot/LICENSE",
  "data/LICENSE",
  "DATA-LICENSE",
  "DATA_LICENSE.md",
];

function firstPresent(candidates: readonly string[]): { path: string; text: string } | undefined {
  for (const candidate of candidates) {
    const full = join(repoRoot, candidate);
    if (existsSync(full)) return { path: candidate, text: readFileSync(full, "utf8") };
  }
  return undefined;
}

/** An SPDX-ish identifier only when the file names one; never guessed. */
function licenceIdentifier(text: string): string | undefined {
  const spdx = text.match(/SPDX-License-Identifier:\s*([\w.\-+]+)/i);
  if (spdx) return spdx[1];
  const known: [RegExp, string][] = [
    [/\bApache License\b[\s\S]{0,80}Version 2\.0/i, "Apache-2.0"],
    [/\bMIT License\b/i, "MIT"],
    [/GNU AFFERO GENERAL PUBLIC LICENSE[\s\S]{0,80}Version 3/i, "AGPL-3.0"],
    [/GNU GENERAL PUBLIC LICENSE[\s\S]{0,80}Version 3/i, "GPL-3.0"],
    [/BSD 3-Clause/i, "BSD-3-Clause"],
    [/Mozilla Public License[\s\S]{0,60}2\.0/i, "MPL-2.0"],
  ];
  for (const [pattern, id] of known) if (pattern.test(text)) return id;
  return undefined;
}

function copyrightNotice(text: string | undefined): string | undefined {
  if (!text) return undefined;
  const line = text
    .split("\n")
    .map((item) => item.trim())
    .find((item) => /^(copyright|\(c\)|©)/i.test(item) && !/^copyright\s*\(c\)\s*<?year>?/i.test(item));
  return line || undefined;
}

const software = firstPresent(LICENCE_FILES);
const data = firstPresent(DATA_LICENCE_FILES);

// A copyright line may live in the licence file or in the README; take the
// first one actually written down, and otherwise record that there is none.
const readme = existsSync(join(repoRoot, "README.md"))
  ? readFileSync(join(repoRoot, "README.md"), "utf8")
  : undefined;

const provenance = {
  repository: canonicalRemote(),
  commit,
  softwareLicense: software
    ? { file: software.path, identifier: licenceIdentifier(software.text) }
    : undefined,
  dataLicense: data ? { file: data.path, identifier: licenceIdentifier(data.text) } : undefined,
  copyright: copyrightNotice(software?.text) ?? copyrightNotice(readme),
};

const body = `// GENERATED by scripts/embed-provenance.ts — do not edit.
//
// What the repository actually declares about itself, captured at build time.
// An \`undefined\` field means the repository does not declare it; the memo
// renderer says so rather than substituting a plausible value.

export interface LicenseRecord {
  /** Repo-relative path of the licence file this came from. */
  readonly file: string;
  /** Identifier only when the file names one. Undefined means unrecognised. */
  readonly identifier?: string;
}

export interface RepoProvenance {
  readonly repository?: string;
  readonly commit?: string;
  readonly softwareLicense?: LicenseRecord;
  readonly dataLicense?: LicenseRecord;
  readonly copyright?: string;
}

export const REPO_PROVENANCE: RepoProvenance = ${JSON.stringify(provenance, null, 2)};
`;

writeFileSync(outFile, body);
console.log(
  `embed-provenance: commit ${provenance.commit?.slice(0, 10) ?? "unknown"}, ` +
    `software licence ${provenance.softwareLicense?.identifier ?? provenance.softwareLicense?.file ?? "none declared"}, ` +
    `data licence ${provenance.dataLicense?.identifier ?? provenance.dataLicense?.file ?? "none declared"}`,
);
