/**
 * Loads vendored JSON Schemas copied from the authoritative `schemas/` tree.
 * Schemas are read from
 * `packages/domain/schemas/` relative to this module so resolution works the
 * same for consumers and for the test runner.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  EMBEDDED_COMPATIBILITY_SCHEMA_TEXT,
  EMBEDDED_CORPUS_COMPATIBILITY_CONTRACT_TEXT,
  EMBEDDED_SCHEMA_TEXT,
} from "./schemas.embedded.js";

/** The canonical set of schema kinds, ordered. */
export const SCHEMA_KINDS = [
  "evidence",
  "source-registry",
  "record",
  "corpus-manifest",
  "corpus-catalog",
  "record-link",
  "legal-policy-record",
  "institutional-record",
  "record-judgment",
] as const;

/** A schema kind, e.g. `"canonical-ir"`. */
export type SchemaKind = (typeof SCHEMA_KINDS)[number];

/** Filename relative to the package's vendored `schemas/` directory for each kind. */
export const SCHEMA_FILES: Readonly<Record<SchemaKind, string>> = Object.freeze({
  evidence: "evidence.schema.json",
  "source-registry": "source-registry.schema.json",
  record: "record.schema.json",
  "corpus-manifest": "corpus-manifest.schema.json",
  "corpus-catalog": "corpus-catalog.schema.json",
  "record-link": "record-link.schema.json",
  "legal-policy-record": "legal-policy-record.schema.json",
  "institutional-record": "institutional-record.schema.json",
  "record-judgment": "record-judgment.schema.json",
});

/** Authoritative path (relative to repository `schemas/`) for each vendored kind. */
export const SCHEMA_AUTHORITY_FILES: Readonly<Record<SchemaKind, string>> = Object.freeze({
  evidence: "core/evidence.schema.json",
  "source-registry": "core/source-registry.schema.json",
  record: "core/record.schema.json",
  "corpus-manifest": "core/corpus-manifest.schema.json",
  "corpus-catalog": "core/corpus-catalog.schema.json",
  "record-link": "core/record-link.schema.json",
  "legal-policy-record": "extensions/legal-policy-record.schema.json",
  "institutional-record": "extensions/institutional-record.schema.json",
  "record-judgment": "analysis/record-judgment.schema.json",
});

/** Versioned compatibility contracts retained for existing native programs. */
export const COMPATIBILITY_SCHEMA_KINDS = [
  "record",
  "legal-policy-record",
  "institutional-record",
  "record-judgment",
] as const;

export type CompatibilitySchemaKind = (typeof COMPATIBILITY_SCHEMA_KINDS)[number];

export const COMPATIBILITY_SCHEMA_FILES: Readonly<Record<CompatibilitySchemaKind, string>> =
  Object.freeze({
    record: "compatibility/record-grammar-v0.1/record.schema.json",
    "legal-policy-record": "compatibility/record-grammar-v0.1/legal-policy-record.schema.json",
    "institutional-record": "compatibility/record-grammar-v0.1/institutional-record.schema.json",
    "record-judgment": "compatibility/record-grammar-v0.1/record-judgment.schema.json",
  });

/**
 * Preserved corpus payload formats that are not a versioned variant of a native
 * record kind. A corpus manifest names one of these by `$id` in its
 * `record_contract` when its files are an imported format rather than a native
 * family grammar, so validation can resolve exactly the declared contract.
 */
export const CORPUS_COMPATIBILITY_CONTRACT_KINDS = ["eu-us-ai-reviewed-document"] as const;

export type CorpusCompatibilityContractKind = (typeof CORPUS_COMPATIBILITY_CONTRACT_KINDS)[number];

export const CORPUS_COMPATIBILITY_CONTRACT_FILES: Readonly<
  Record<CorpusCompatibilityContractKind, string>
> = Object.freeze({
  "eu-us-ai-reviewed-document":
    "compatibility/eu-us-ai-reviewed-v1/reviewed-corpus-document.schema.json",
});

/** A JSON Schema document as a plain object. */
export type JsonSchema = Record<string, unknown>;

const SCHEMAS_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "schemas");

function loadSchema(kind: SchemaKind): JsonSchema {
  // Parse from the inlined text (schemas.embedded.ts) rather than reading the
  // file: `import.meta.url` is rewritten to a build-time path by bundlers, so a
  // filesystem read here breaks inside a serverless bundle. The embedded text is
  // regenerated by `embed-schemas`, so it stays byte-identical to the vendor directory.
  return JSON.parse(EMBEDDED_SCHEMA_TEXT[kind]) as JsonSchema;
}

/** The parsed schema document for each kind, loaded once and frozen. */
export const RAW_SCHEMAS: Readonly<Record<SchemaKind, JsonSchema>> = Object.freeze(
  Object.fromEntries(SCHEMA_KINDS.map((kind) => [kind, Object.freeze(loadSchema(kind))])) as Record<
    SchemaKind,
    JsonSchema
  >,
);

export const RAW_COMPATIBILITY_SCHEMAS: Readonly<Record<CompatibilitySchemaKind, JsonSchema>> =
  Object.freeze(
    Object.fromEntries(
      COMPATIBILITY_SCHEMA_KINDS.map((kind) => [
        kind,
        Object.freeze(JSON.parse(EMBEDDED_COMPATIBILITY_SCHEMA_TEXT[kind]) as JsonSchema),
      ]),
    ) as Record<CompatibilitySchemaKind, JsonSchema>,
  );

export const RAW_CORPUS_COMPATIBILITY_CONTRACTS: Readonly<
  Record<CorpusCompatibilityContractKind, JsonSchema>
> = Object.freeze(
  Object.fromEntries(
    CORPUS_COMPATIBILITY_CONTRACT_KINDS.map((kind) => [
      kind,
      Object.freeze(JSON.parse(EMBEDDED_CORPUS_COMPATIBILITY_CONTRACT_TEXT[kind]) as JsonSchema),
    ]),
  ) as Record<CorpusCompatibilityContractKind, JsonSchema>,
);

/** The declared `$id` of each schema. */
export const SCHEMA_IDS: Readonly<Record<SchemaKind, string>> = Object.freeze(
  Object.fromEntries(
    SCHEMA_KINDS.map((kind) => [kind, String(RAW_SCHEMAS[kind].$id ?? "")]),
  ) as Record<SchemaKind, string>,
);

/** Read the raw bytes of a vendored schema file (used by the drift guard). */
export function readVendoredSchemaText(kind: SchemaKind): string {
  return readFileSync(join(SCHEMAS_DIR, SCHEMA_FILES[kind]), "utf8");
}

/** Absolute path to the vendored schema directory. */
export const VENDORED_SCHEMAS_DIR = SCHEMAS_DIR;

/** Return true if a string is a known schema kind. */
export function isSchemaKind(value: string): value is SchemaKind {
  return (SCHEMA_KINDS as readonly string[]).includes(value);
}
