// AUTO-GENERATED by apps/web/scripts/embed-corpus-catalog.ts — do not edit by hand.
// Source: corpora/catalog.yaml and the native corpus manifests it references.

export type CatalogCorpusFamily = "legal_policy" | "institutional";
export type CatalogCorpusStatus = "active" | "draft";

export interface CatalogCorpusSummary {
  readonly corpusId: string;
  readonly family: CatalogCorpusFamily;
  readonly jurisdiction: string;
  readonly status: CatalogCorpusStatus;
  readonly title: string;
  readonly issuer: string;
  readonly identity: string;
  readonly path: string;
}

export const CORPUS_CATALOG_SOURCE = "corpora/catalog.yaml";
// prettier-ignore
export const CORPUS_CATALOG: readonly CatalogCorpusSummary[] = Object.freeze([
  {
    "corpusId": "writ.corpus.legal-policy.eu.european-union.artificial-intelligence-act-2024-1689",
    "family": "legal_policy",
    "jurisdiction": "EU",
    "status": "active",
    "title": "European Union Artificial Intelligence Act 2024/1689",
    "issuer": "European Union",
    "identity": "EU_AI_ACT",
    "path": "corpora/legal-policy/eu/european-union/artificial-intelligence-act-2024-1689"
  },
  {
    "corpusId": "writ.corpus.legal-policy.eu.european-commission.gpai-guidelines",
    "family": "legal_policy",
    "jurisdiction": "EU",
    "status": "active",
    "title": "European Commission GPAI Guidelines",
    "issuer": "European Commission",
    "identity": "COMMISSION_GPAI_GUIDELINES",
    "path": "corpora/legal-policy/eu/european-commission/gpai-guidelines"
  },
  {
    "corpusId": "writ.corpus.legal-policy.eu.european-commission.gpai-code-of-practice-signatory-notice",
    "family": "legal_policy",
    "jurisdiction": "EU",
    "status": "active",
    "title": "European Commission GPAI Code of Practice signatory notice",
    "issuer": "European Commission",
    "identity": "writ.corpus.legal-policy.eu.european-commission.gpai-code-of-practice-signatory-notice",
    "path": "corpora/legal-policy/eu/european-commission/gpai-code-of-practice-signatory-notice"
  },
  {
    "corpusId": "writ.corpus.legal-policy.us.nist.ai-risk-management-framework-1-0",
    "family": "legal_policy",
    "jurisdiction": "US",
    "status": "active",
    "title": "NIST AI Risk Management Framework 1.0",
    "issuer": "NIST",
    "identity": "NIST_AI_RMF",
    "path": "corpora/legal-policy/us/nist/ai-risk-management-framework-1-0"
  },
  {
    "corpusId": "writ.corpus.legal-policy.us.nist.ai-risk-management-framework-playbook",
    "family": "legal_policy",
    "jurisdiction": "US",
    "status": "active",
    "title": "NIST AI Risk Management Framework Playbook",
    "issuer": "NIST",
    "identity": "NIST_AI_RMF_PLAYBOOK",
    "path": "corpora/legal-policy/us/nist/ai-risk-management-framework-playbook"
  },
  {
    "corpusId": "writ.corpus.legal-policy.us.nist.generative-ai-profile",
    "family": "legal_policy",
    "jurisdiction": "US",
    "status": "active",
    "title": "NIST Generative AI Profile",
    "issuer": "NIST",
    "identity": "NIST_GENERATIVE_AI_PROFILE",
    "path": "corpora/legal-policy/us/nist/generative-ai-profile"
  },
  {
    "corpusId": "writ.corpus.legal-policy.us.nist.caisi.overview",
    "family": "legal_policy",
    "jurisdiction": "US",
    "status": "active",
    "title": "CAISI overview",
    "issuer": "NIST",
    "identity": "writ.corpus.legal-policy.us.nist.caisi.overview",
    "path": "corpora/legal-policy/us/nist/caisi/overview"
  },
  {
    "corpusId": "writ.corpus.legal-policy.us.nist.caisi.guidelines",
    "family": "legal_policy",
    "jurisdiction": "US",
    "status": "active",
    "title": "CAISI guidelines",
    "issuer": "NIST",
    "identity": "writ.corpus.legal-policy.us.nist.caisi.guidelines",
    "path": "corpora/legal-policy/us/nist/caisi/guidelines"
  },
  {
    "corpusId": "writ.corpus.legal-policy.us.office-of-management-and-budget.m-25-21",
    "family": "legal_policy",
    "jurisdiction": "US",
    "status": "active",
    "title": "OMB Memorandum M-25-21",
    "issuer": "Office of Management and Budget",
    "identity": "OMB_M_25_21",
    "path": "corpora/legal-policy/us/office-of-management-and-budget/m-25-21"
  },
  {
    "corpusId": "writ.corpus.legal-policy.us.office-of-management-and-budget.m-25-22",
    "family": "legal_policy",
    "jurisdiction": "US",
    "status": "active",
    "title": "OMB Memorandum M-25-22",
    "issuer": "Office of Management and Budget",
    "identity": "OMB_M_25_22",
    "path": "corpora/legal-policy/us/office-of-management-and-budget/m-25-22"
  },
  {
    "corpusId": "writ.corpus.legal-policy.us.white-house.ai-leadership-fact-sheet-2025-01",
    "family": "legal_policy",
    "jurisdiction": "US",
    "status": "active",
    "title": "White House AI leadership fact sheet (January 2025)",
    "issuer": "White House",
    "identity": "writ.corpus.legal-policy.us.white-house.ai-leadership-fact-sheet-2025-01",
    "path": "corpora/legal-policy/us/white-house/ai-leadership-fact-sheet-2025-01"
  },
  {
    "corpusId": "writ.corpus.legal-policy.us.white-house.national-ai-policy-framework-fact-sheet-2025-12",
    "family": "legal_policy",
    "jurisdiction": "US",
    "status": "active",
    "title": "White House national AI policy framework fact sheet (December 2025)",
    "issuer": "White House",
    "identity": "writ.corpus.legal-policy.us.white-house.national-ai-policy-framework-fact-sheet-2025-12",
    "path": "corpora/legal-policy/us/white-house/national-ai-policy-framework-fact-sheet-2025-12"
  },
  {
    "corpusId": "writ.corpus.legal-policy.us.white-house.americas-ai-action-plan",
    "family": "legal_policy",
    "jurisdiction": "US",
    "status": "active",
    "title": "America's AI Action Plan",
    "issuer": "White House",
    "identity": "writ.corpus.legal-policy.us.white-house.americas-ai-action-plan",
    "path": "corpora/legal-policy/us/white-house/americas-ai-action-plan"
  },
  {
    "corpusId": "us.constitutional_law",
    "family": "legal_policy",
    "jurisdiction": "US",
    "status": "draft",
    "title": "United States constitutional law",
    "issuer": "US",
    "identity": "us.constitutional_law",
    "path": "corpora/legal-policy/us/constitutional-law"
  },
  {
    "corpusId": "eu.institutions.european_commission",
    "family": "institutional",
    "jurisdiction": "EU",
    "status": "draft",
    "title": "European Commission institutional facts",
    "issuer": "European Commission",
    "identity": "european_commission",
    "path": "corpora/institutional/eu/european-commission"
  },
  {
    "corpusId": "us.institutions.nist",
    "family": "institutional",
    "jurisdiction": "US",
    "status": "draft",
    "title": "National Institute of Standards and Technology institutional facts",
    "issuer": "National Institute of Standards and Technology",
    "identity": "nist",
    "path": "corpora/institutional/us/nist"
  }
]);
