/**
 * Markdown export for a policy memo.
 *
 * The exported file has to stand on its own once it leaves the site, so it
 * carries where it came from: the reviewed dataset, the Writ profile, the
 * repository and the commit. That is provenance, which is a different thing
 * from permission — the rights block states what the repository actually
 * declares, and where it declares nothing, it says so rather than implying a
 * grant that was never made.
 *
 * A pure function of the memo, the repository facts and a timestamp, so the
 * same memo exported twice differs only in the timestamp.
 */

import type { Memo, MemoSentence } from "./demo-memo.js";
import type { RepoProvenance } from "./repo-provenance.js";
import { humanize } from "./demo-analysis-format.js";

/** Superscript-style citation run: `[1][2][3]` collapses to `[1–3]`. */
export function citationRun(notes: readonly number[]): string {
  if (notes.length === 0) return "";
  const sorted = [...notes].sort((a, b) => a - b);
  const parts: string[] = [];
  let start = sorted[0];
  let previous = sorted[0];
  for (const n of sorted.slice(1).concat(Number.NaN)) {
    if (n === previous + 1) {
      previous = n;
      continue;
    }
    parts.push(
      start === previous
        ? String(start)
        : previous === start + 1
          ? `${start}, ${previous}`
          : `${start}–${previous}`,
    );
    start = n;
    previous = n;
  }
  return parts.join(", ");
}

function renderSentences(sentences: readonly MemoSentence[]): string {
  return sentences
    .map((sentence) =>
      sentence.notes.length > 0
        ? `${sentence.text}[^${citationRun(sentence.notes)}]`
        : sentence.text,
    )
    .join(" ");
}

/**
 * Markdown footnote labels cannot hold a range, so a sentence resting on
 * several records gets one marker per record. The prose above uses ranges for
 * readability; here correctness of the link matters more.
 */
function renderSentencesWithMarkers(sentences: readonly MemoSentence[]): string {
  return sentences
    .map((sentence) => `${sentence.text}${sentence.notes.map((n) => `[^${n}]`).join("")}`)
    .join(" ");
}

const NOT_DECLARED = "not-declared";

export interface ExportOptions {
  memo: Memo;
  provenance: RepoProvenance;
  /** ISO-8601, read at download time. */
  generatedAt: string;
}

export function memoToMarkdown({ memo, provenance, generatedAt }: ExportOptions): string {
  const repository = provenance.repository ?? NOT_DECLARED;
  const commit = provenance.commit ?? NOT_DECLARED;
  const softwareLicence =
    provenance.softwareLicense?.identifier ?? provenance.softwareLicense?.file ?? NOT_DECLARED;
  const dataLicence =
    provenance.dataLicense?.identifier ?? provenance.dataLicense?.file ?? NOT_DECLARED;

  const lines: string[] = [];

  // --- front matter --------------------------------------------------------
  lines.push("---");
  lines.push("generated_by: Writ");
  lines.push("document_type: policy_memo");
  lines.push(`question_id: ${memo.questionId}`);
  lines.push(`dataset_id: ${memo.datasetId}`);
  lines.push(`profile_id: ${memo.profileId}`);
  lines.push(`generated_at: ${generatedAt}`);
  lines.push(`repository: ${repository}`);
  lines.push(`commit: ${commit}`);
  lines.push(`license: ${softwareLicence}`);
  lines.push("---");
  lines.push("");
  lines.push(`<!-- Generated by Writ | profile:${memo.profileId} | commit:${commit} -->`);
  lines.push("");

  // --- the memo ------------------------------------------------------------
  lines.push(`# ${memo.title}`);
  lines.push("");
  lines.push("*written in Writ.*");
  lines.push("");
  lines.push(`**Question.** ${memo.question}`);
  lines.push("");
  lines.push("## Executive finding");
  lines.push("");
  lines.push(renderSentencesWithMarkers(memo.executive));
  lines.push("");

  for (const section of memo.sections) {
    lines.push(`## ${section.heading}`);
    lines.push("");
    lines.push(`*${section.purpose}*`);
    lines.push("");
    for (const paragraph of section.paragraphs) {
      lines.push(renderSentencesWithMarkers(paragraph));
      lines.push("");
    }
  }

  lines.push("## Conclusion");
  lines.push("");
  lines.push(renderSentencesWithMarkers(memo.conclusion));
  lines.push("");

  // --- sources -------------------------------------------------------------
  lines.push("## Sources");
  lines.push("");
  for (const note of memo.records) {
    if (note.n === undefined) continue;
    const where = note.document ? ` ${note.document.anchor}`.trimEnd() : "";
    const head = `[^${note.n}]: **${note.claimId}** · ${note.jurisdiction} · ${note.instrument}, ${note.sourceLocator}${where}.`;
    const parts = [head];
    if (note.excerpt) {
      parts.push(`  > “${note.excerpt}”`);
    } else {
      parts.push(
        "  This record has not yet been traced to its source document, so no excerpt is quoted.",
      );
    }
    parts.push(`  Reviewed interpretation: ${note.interpretation}`);
    parts.push(
      `  Legal force: ${humanize(note.legalForce)}. Applicability: ${humanize(note.applicabilityStatus)}. Enforcement: ${note.enforcementStatus}.`,
    );
    if (note.document) {
      parts.push(
        `  Source: ${note.document.title} — ${note.document.uri} (retrieved ${note.document.retrievedAt}).`,
      );
    }
    lines.push(parts.join("\n"));
    lines.push("");
  }

  // Everything the memo drew on, cited inline or not, so an aggregate sentence
  // in the prose can still be checked against the records behind it.
  lines.push("## Records considered");
  lines.push("");
  for (const record of memo.records) {
    const marker = record.n !== undefined ? `[${record.n}] ` : "";
    lines.push(
      `- ${marker}**${record.claimId}** · ${record.jurisdiction} · ${record.instrument}, ${record.sourceLocator}` +
        (record.excerpt
          ? `\n  > “${record.excerpt}”`
          : "\n  Not yet traced to a source document.") +
        `\n  ${record.interpretation}` +
        `\n  Legal force: ${humanize(record.legalForce)}. Applicability: ${humanize(record.applicabilityStatus)}. Enforcement: ${record.enforcementStatus}.`,
    );
  }
  lines.push("");

  lines.push(
    `Drawn from ${memo.coverage.selected} of ${memo.coverage.corpus} reviewed claims across ${memo.coverage.documents} source documents.` +
      (memo.coverage.untraced.length
        ? ` ${memo.coverage.untraced.length} selected claims are not yet traced to a source document (${memo.coverage.untraced.join(", ")}) and are cited without an excerpt.`
        : ""),
  );
  lines.push("");

  // --- attribution ---------------------------------------------------------
  lines.push("---");
  lines.push("");
  lines.push("**written in Writ.**");
  lines.push("");
  lines.push(
    "This policy memo was compiled from human-reviewed Writ profiles and source-linked claims. Its findings can be traced to the records and footnotes included above.",
  );
  lines.push("");
  lines.push("**Provenance**");
  lines.push(`- Writ profile: \`${memo.profileId}\``);
  lines.push(`- Reviewed dataset: \`${memo.datasetId}\``);
  lines.push(`- Repository: ${repository}`);
  lines.push(`- Version: \`${commit}\``);
  lines.push(`- Generated: ${generatedAt}`);
  lines.push("");
  lines.push(
    "The repository link and commit identify the exact version this memo was produced from, so it can be regenerated and checked. They record provenance; they do not establish ownership or grant permission to reuse.",
  );
  lines.push("");
  lines.push("**Rights and licence**");
  if (provenance.copyright) {
    lines.push(`${provenance.copyright}.`);
  } else {
    lines.push("The repository states no copyright notice.");
  }
  lines.push(
    provenance.softwareLicense
      ? `Software: \`${softwareLicence}\` (see \`${provenance.softwareLicense.file}\`).`
      : "Software: the repository contains no licence file, so no licence is granted for the software.",
  );
  lines.push(
    provenance.dataLicense
      ? `Data and written analysis: \`${dataLicence}\` (see \`${provenance.dataLicense.file}\`).`
      : "Data and written analysis: the repository declares no separate licence for the reviewed annotations or this analysis. A software licence, where one exists, does not govern them.",
  );
  lines.push(
    "Quoted excerpts remain subject to the terms of the authorities that issued the documents they are taken from.",
  );
  lines.push("");

  return lines.join("\n");
}

/** A stable filename for the download. */
export function memoFilename(memo: Memo): string {
  return `writ-memo-${memo.questionId}.md`;
}

export { renderSentences };
