// AUTO-GENERATED by scripts/embed-policy-test.ts — do not edit by hand.
// The human-reviewed EU–US AI evaluation pilot, parsed at build time from
// archive/pilots/eu-us-ai-evaluation-v1/original/annotations/human-reviewed.yaml. That YAML is the single authoritative
// copy of this data; this file is a projection of it, not a second source.
// Regenerated by the web app's `embed` and `build` scripts.

import type { ReviewedDataset } from "./policy-test";

export const POLICY_TEST_SOURCE_PATH = "archive/pilots/eu-us-ai-evaluation-v1/original/annotations/human-reviewed.yaml";

export const POLICY_TEST_DATASET: ReviewedDataset = {
  "schema_version": "1.0",
  "dataset_id": "eu_us_ai_evaluation_pilot_human_reviewed",
  "review_status": "human_reviewed",
  "pilot_question": "Does the jurisdiction currently impose a binding model-evaluation requirement on providers of advanced or general-purpose AI models?",
  "methodology": {
    "us_scope": {
      "included": [
        "cross_sector",
        "government_use",
        "government_procurement"
      ],
      "excluded": [
        "national_security_only"
      ]
    },
    "actor_types": [
      "market_provider",
      "government_vendor",
      "federal_agency",
      "ai_lifecycle_organization",
      "downstream_provider",
      "ecosystem_stakeholder"
    ],
    "core_conduct_types": [
      "model_evaluation",
      "evaluation_documentation",
      "risk_assessment"
    ],
    "code_of_practice": {
      "legal_force": "voluntary",
      "compliance_function": "recognized_compliance_path"
    },
    "lifecycle_dimensions": [
      "adoption_status",
      "applicability_status",
      "enforcement_status"
    ],
    "headline_rule": {
      "legal_force": "binding",
      "applicability_status": "applicable",
      "actor_type": "market_provider",
      "conduct_type": "model_evaluation",
      "target_class": "advanced_or_general_purpose_ai_model"
    }
  },
  "reconciliation": {
    "row_order_authority": "uploaded_annotation_table",
    "removed_from_main_reviewed_corpus": [
      {
        "temporary_row_id": "EU-06",
        "source_locator": "Article 51(1)-(2)",
        "reason": "This scope-rule passage was incorrectly assigned the EU-06 identifier and is not EU-06 in the uploaded table."
      },
      {
        "temporary_row_id": "EU-07",
        "source_locator": "Article 52(1)",
        "reason": "This notification passage was incorrectly assigned the EU-07 identifier and is not EU-07 in the uploaded table."
      }
    ],
    "corrected_numbering": [
      {
        "previous_row_id": "EU-02",
        "source_locator": "Article 55(1)(a)",
        "corrected_row_id": "EU-06"
      },
      {
        "previous_row_id": "EU-03",
        "source_locator": "Article 55(1)(b)",
        "corrected_row_id": "EU-07"
      },
      {
        "previous_row_id": "EU-04",
        "source_locator": "Article 55(1)(c)",
        "corrected_row_id": "EU-08"
      },
      {
        "previous_row_id": "EU-05",
        "source_locator": "Article 55(1)(d)",
        "corrected_row_id": "EU-09"
      }
    ]
  },
  "records": [
    {
      "row_id": "EU-01",
      "review_decision": "accepted",
      "jurisdiction": "EU",
      "instrument": "EU_AI_ACT",
      "source_locator": "Article 53(1)(a)",
      "record_type": "obligation",
      "actor_type": "market_provider",
      "actor_term_local": "provider of a general-purpose AI model",
      "conduct_type": "evaluation_documentation",
      "conduct_term_local": "draw up and maintain technical documentation, including training, testing and evaluation results",
      "legal_force": "binding",
      "compliance_function": "direct_obligation",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "unknown",
      "responsible_authority": "European Commission",
      "implementation_body": "AI Office",
      "additional_authority": "competent national authorities",
      "scope": [
        "cross_sector"
      ],
      "target_system": "general_purpose_ai_model",
      "headline_relevance": "supporting_only",
      "interpretation_note": "The provision requires documentation that includes evaluation results but does not independently create a direct duty to perform model evaluation."
    },
    {
      "row_id": "EU-02",
      "review_decision": "accepted",
      "jurisdiction": "EU",
      "instrument": "EU_AI_ACT",
      "source_locator": "Article 53(1)(b)",
      "record_type": "obligation",
      "actor_type": "market_provider",
      "actor_term_local": "provider of a general-purpose AI model",
      "recipient_actor_type": "downstream_provider",
      "recipient_actor_term_local": "provider intending to integrate the general-purpose AI model into an artificial-intelligence system",
      "conduct_type": "downstream_documentation",
      "conduct_term_local": "provide information and documentation to downstream artificial-intelligence system providers",
      "legal_force": "binding",
      "compliance_function": "direct_obligation",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "unknown",
      "responsible_authority": "European Commission",
      "implementation_body": "AI Office",
      "additional_authority": "competent national authorities",
      "scope": [
        "cross_sector"
      ],
      "target_system": "general_purpose_ai_model",
      "headline_relevance": "supporting_only",
      "interpretation_note": "This is a binding information and documentation obligation for downstream integration. It may support evaluation and oversight but does not itself require the GPAI provider to perform model evaluation."
    },
    {
      "row_id": "EU-03",
      "review_decision": "accepted",
      "jurisdiction": "EU",
      "instrument": "EU_AI_ACT",
      "source_locator": "Article 53(1)(c)",
      "record_type": "obligation",
      "actor_type": "market_provider",
      "actor_term_local": "provider of a general-purpose AI model",
      "conduct_type": "copyright_policy",
      "conduct_term_local": "put in place a policy to comply with Union copyright law",
      "legal_force": "binding",
      "compliance_function": "direct_obligation",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "unknown",
      "responsible_authority": "European Commission",
      "implementation_body": "AI Office",
      "additional_authority": "competent national authorities",
      "scope": [
        "cross_sector"
      ],
      "target_system": "general_purpose_ai_model",
      "headline_relevance": "contextual_only",
      "interpretation_note": "This is a binding copyright-compliance policy obligation. It does not require model evaluation, testing or risk assessment."
    },
    {
      "row_id": "EU-04",
      "review_decision": "accepted",
      "jurisdiction": "EU",
      "instrument": "EU_AI_ACT",
      "source_locator": "Article 53(1)(d)",
      "record_type": "obligation",
      "actor_type": "market_provider",
      "actor_term_local": "provider of a general-purpose AI model",
      "conduct_type": "training_content_summary",
      "conduct_term_local": "draw up and make publicly available a sufficiently detailed summary of the content used to train the model",
      "legal_force": "binding",
      "compliance_function": "direct_obligation",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "unknown",
      "responsible_authority": "European Commission",
      "implementation_body": "AI Office",
      "scope": [
        "cross_sector"
      ],
      "target_system": "general_purpose_ai_model",
      "headline_relevance": "contextual_only",
      "interpretation_note": "This is a binding public-transparency obligation concerning training content. It does not require model evaluation, testing or risk assessment."
    },
    {
      "row_id": "EU-05",
      "review_decision": "accepted",
      "jurisdiction": "EU",
      "instrument": "EU_AI_ACT",
      "source_locator": "Article 53(2)",
      "record_type": "exception_rule",
      "actor_type": "market_provider",
      "actor_term_local": "open-source general-purpose AI model provider",
      "defined_actor_class": "open_source_gpai_provider",
      "exception_scope_local": "possible exemption from some Article 53 documentation obligations",
      "exception_target": [
        "specified_Article_53_documentation_obligations"
      ],
      "exception_conditions_status": "statutory conditions apply but are not fully encoded from the uploaded annotation table",
      "legal_force": "binding",
      "source_legal_force_label": "binding_exception",
      "compliance_function": "obligation_exception",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "unknown",
      "responsible_authority": "European Commission",
      "implementation_body": "AI Office",
      "scope": [
        "cross_sector"
      ],
      "target_system": "open_source_general_purpose_ai_model",
      "headline_relevance": "qualifies_baseline_obligations",
      "interpretation_note": "Article 53(2) provides a conditional exception from specified Article 53 documentation obligations for qualifying open-source GPAI providers. It does not create a general exemption from the AI Act or erase every obligation that may apply."
    },
    {
      "row_id": "EU-06",
      "review_decision": "accepted",
      "jurisdiction": "EU",
      "instrument": "EU_AI_ACT",
      "source_locator": "Article 55(1)(a)",
      "record_type": "obligation",
      "actor_type": "market_provider",
      "actor_term_local": "provider of a general-purpose AI model with systemic risk",
      "conduct_type": "model_evaluation",
      "conduct_term_local": "perform model evaluation using standardized protocols and state-of-the-art tools, including adversarial testing",
      "legal_force": "binding",
      "compliance_function": "direct_obligation",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "unknown",
      "responsible_authority": "European Commission",
      "implementation_body": "AI Office",
      "target_system": "general_purpose_ai_model_with_systemic_risk",
      "headline_relevance": "directly_satisfies_for_defined_class",
      "interpretation_note": "This is the clearest EU positive example of a binding and currently applicable model-evaluation duty for a defined class of market providers."
    },
    {
      "row_id": "EU-07",
      "review_decision": "accepted",
      "jurisdiction": "EU",
      "instrument": "EU_AI_ACT",
      "source_locator": "Article 55(1)(b)",
      "record_type": "obligation",
      "actor_type": "market_provider",
      "actor_term_local": "provider of a general-purpose AI model with systemic risk",
      "conduct_type": "risk_assessment",
      "conduct_term_local": "assess possible systemic risks at Union level",
      "legal_force": "binding",
      "compliance_function": "direct_obligation",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "unknown",
      "responsible_authority": "European Commission",
      "implementation_body": "AI Office",
      "target_system": "general_purpose_ai_model_with_systemic_risk",
      "headline_relevance": "supporting_only",
      "interpretation_note": "The systemic-risk assessment obligation supports evaluation governance but remains distinct from the direct model-evaluation duty."
    },
    {
      "row_id": "EU-08",
      "review_decision": "accepted",
      "jurisdiction": "EU",
      "instrument": "EU_AI_ACT",
      "source_locator": "Article 55(1)(c)",
      "record_type": "obligation",
      "actor_type": "market_provider",
      "actor_term_local": "provider of a general-purpose AI model with systemic risk",
      "conduct_type": "incident_reporting",
      "conduct_term_local": "report relevant information about serious incidents and possible corrective measures",
      "source_actions": [
        "incident_tracking",
        "incident_documentation",
        "incident_reporting"
      ],
      "legal_force": "binding",
      "compliance_function": "direct_obligation",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "unknown",
      "responsible_authority": "European Commission",
      "implementation_body": "AI Office",
      "additional_authority": "national competent authorities, where appropriate",
      "target_system": "general_purpose_ai_model_with_systemic_risk",
      "headline_relevance": "contextual_support",
      "interpretation_note": "Incident reporting is binding within the systemic-risk regime, but it is distinct from model evaluation."
    },
    {
      "row_id": "EU-09",
      "review_decision": "accepted",
      "jurisdiction": "EU",
      "instrument": "EU_AI_ACT",
      "source_locator": "Article 55(1)(d)",
      "record_type": "obligation",
      "actor_type": "market_provider",
      "actor_term_local": "provider of a general-purpose AI model with systemic risk",
      "conduct_type": "cybersecurity_protection",
      "conduct_term_local": "ensure an appropriate level of cybersecurity protection for the model and its infrastructure",
      "legal_force": "binding",
      "compliance_function": "direct_obligation",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "unknown",
      "responsible_authority": "European Commission",
      "implementation_body": "AI Office",
      "target_system": "general_purpose_ai_model_with_systemic_risk",
      "headline_relevance": "contextual_support",
      "interpretation_note": "Cybersecurity protection is a distinct binding duty but does not independently establish a model-evaluation obligation."
    },
    {
      "row_id": "EU-10",
      "review_decision": "accepted",
      "jurisdiction": "EU",
      "instrument": "COMMISSION_GPAI_GUIDELINES",
      "source_locator": "Commission GPAI guidelines",
      "record_type": "source_bundle",
      "derived_claims": [
        {
          "claim_id": "EU-10A",
          "record_type": "interpretive_guidance",
          "actor_type": "market_provider",
          "actor_relationship": "possible_provider",
          "actor_term_local": "provider or undertaking determining whether it is the provider of a general-purpose AI model",
          "conduct_type": "regulatory_classification",
          "conduct_term_local": "determine whether the model qualifies as a general-purpose AI model",
          "classification_indicators": {
            "indicative_gpai_compute_threshold": "10^23_FLOP",
            "systemic_risk_presumption_threshold": "10^25_FLOP"
          },
          "legal_force": "interpretive",
          "compliance_function": "implementation_guidance",
          "adoption_status": "adopted",
          "applicability_status": "applicable",
          "enforcement_status": "not_applicable",
          "responsible_authority": "European Commission",
          "implementation_body": "AI Office",
          "headline_relevance": "defines_scope"
        },
        {
          "claim_id": "EU-10B",
          "record_type": "obligation",
          "actor_type": "market_provider",
          "actor_term_local": "provider of a general-purpose AI model meeting or expected to meet the systemic-risk compute threshold",
          "conduct_type": "regulatory_notification",
          "conduct_term_local": "notify the Commission when the systemic-risk threshold is met or expected to be met",
          "source_instrument_force": "interpretive",
          "described_obligation_force": "binding",
          "legal_force": "binding",
          "compliance_function": "direct_obligation",
          "adoption_status": "adopted",
          "applicability_status": "applicable",
          "enforcement_status": "unknown",
          "responsible_authority": "European Commission",
          "implementation_body": "AI Office",
          "target_system": "general_purpose_ai_model_meeting_systemic_risk_threshold",
          "headline_relevance": "scope_activation_support"
        },
        {
          "claim_id": "EU-10C",
          "record_type": "compliance_path",
          "actor_type": "market_provider",
          "actor_term_local": "provider of a general-purpose AI model",
          "conduct_type": "compliance_demonstration",
          "conduct_term_local": "rely on adherence to the Code of Practice as a means of demonstrating compliance with relevant AI Act obligations",
          "legal_force": "voluntary",
          "compliance_function": "recognized_compliance_path",
          "adoption_status": "adopted",
          "applicability_status": "applicable",
          "enforcement_status": "not_applicable",
          "responsible_authority": "European Commission",
          "implementation_body": "AI Office",
          "headline_relevance": "contextual_support"
        }
      ],
      "interpretation_note": "The guidelines are interpretive and do not independently create statutory duties. The notification duty remains binding because it originates in the AI Act. Use of the Code of Practice is voluntary and functions as a recognized compliance path."
    },
    {
      "row_id": "EU-11",
      "review_decision": "accepted",
      "jurisdiction": "EU",
      "instrument": "EU_AI_ACT",
      "source_locator": "Article 113 application timetable",
      "record_type": "source_bundle",
      "derived_claims": [
        {
          "claim_id": "EU-11A",
          "record_type": "lifecycle_rule",
          "target_actor": "market_provider",
          "target_system": "general_purpose_ai_model",
          "legal_force": "binding",
          "adoption_status": "adopted",
          "applicability_status": "applicable",
          "effective_from": "2025-08-02",
          "enforcement_status": "unknown",
          "responsible_authority": "European Commission",
          "headline_relevance": "establishes_current_applicability"
        },
        {
          "claim_id": "EU-11B",
          "record_type": "lifecycle_rule",
          "target_actor": "market_provider",
          "target_system": "general-purpose AI model placed on the market before 2025-08-02",
          "legal_force": "binding",
          "adoption_status": "adopted",
          "applicability_status": "transition_for_existing_models",
          "compliance_deadline": "2027-08-02",
          "enforcement_status": "unknown",
          "responsible_authority": "European Commission",
          "headline_relevance": "qualifies_current_applicability"
        }
      ],
      "interpretation_note": "Article 113 is a binding lifecycle rule rather than a separate model-evaluation obligation."
    },
    {
      "row_id": "EU-12",
      "review_decision": "accepted",
      "jurisdiction": "EU",
      "instrument": "GPAI_CODE_OF_PRACTICE_SIGNATORY_NOTICE",
      "source_locator": "AI Office signatory notice",
      "record_type": "compliance_path",
      "actor_type": "market_provider",
      "actor_term_local": "provider of a general-purpose AI model choosing to become a signatory to the Code of Practice",
      "conduct_type": "compliance_demonstration",
      "conduct_term_local": "adhere to the General-Purpose AI Code of Practice as a means of demonstrating compliance with relevant AI Act obligations",
      "legal_force": "voluntary",
      "compliance_function": "recognized_compliance_path",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "not_applicable",
      "responsible_authority": "European Commission",
      "implementation_body": "AI Office",
      "underlying_regime_force": "binding",
      "underlying_instrument": "EU_AI_ACT",
      "headline_relevance": "contextual_support",
      "interpretation_note": "The Code is voluntary but operates as a recognized route for demonstrating compliance with binding statutory duties."
    },
    {
      "row_id": "US-01",
      "review_decision": "accepted",
      "jurisdiction": "US",
      "instrument": "NIST_AI_RMF",
      "source_locator": "abstract",
      "record_type": "guidance",
      "actor_type": "ai_lifecycle_organization",
      "actor_term_local": "organization designing, developing, deploying or using AI",
      "conduct_type": "risk_management",
      "conduct_term_local": "use the AI Risk Management Framework to manage risks associated with artificial intelligence",
      "legal_force": "voluntary",
      "compliance_function": "general_guidance",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "not_applicable",
      "responsible_authority": "NIST",
      "scope": [
        "cross_sector"
      ],
      "target_system": "artificial_intelligence_system",
      "headline_relevance": "voluntary_framework_support",
      "interpretation_note": "The AI RMF is an active cross-sector framework but does not establish a binding model-evaluation duty for private providers."
    },
    {
      "row_id": "US-02",
      "review_decision": "accepted",
      "jurisdiction": "US",
      "instrument": "NIST_AI_RMF_PLAYBOOK",
      "source_locator": "overview",
      "record_type": "implementation_guidance",
      "actor_type": "ai_lifecycle_organization",
      "actor_term_local": "organization using the AI Risk Management Framework",
      "conduct_type": "risk_management",
      "conduct_term_local": "use suggested actions across the Govern, Map, Measure and Manage functions",
      "framework_functions": [
        "govern",
        "map",
        "measure",
        "manage"
      ],
      "legal_force": "voluntary",
      "compliance_function": "implementation_guidance",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "not_applicable",
      "responsible_authority": "NIST",
      "scope": [
        "cross_sector"
      ],
      "target_system": "artificial_intelligence_system",
      "headline_relevance": "voluntary_framework_support",
      "interpretation_note": "The Playbook provides voluntary implementation guidance. Its overview does not independently require model evaluation."
    },
    {
      "row_id": "US-03",
      "review_decision": "accepted",
      "jurisdiction": "US",
      "instrument": "NIST_GENERATIVE_AI_PROFILE",
      "source_locator": "abstract",
      "record_type": "guidance",
      "actor_type": "ai_lifecycle_organization",
      "actor_term_local": "organization designing, developing, using or evaluating generative artificial intelligence",
      "conduct_type": "model_evaluation",
      "conduct_term_local": "use the Generative AI Profile to incorporate trustworthiness considerations into the evaluation of generative AI systems",
      "source_lifecycle_activities": [
        "design",
        "development",
        "use",
        "evaluation"
      ],
      "legal_force": "voluntary",
      "compliance_function": "evaluation_guidance",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "not_applicable",
      "responsible_authority": "NIST",
      "scope": [
        "cross_sector"
      ],
      "target_system": "generative_ai_system",
      "headline_relevance": "voluntary_evaluation_support",
      "interpretation_note": "The Profile directly concerns evaluation, but its voluntary status means it does not create a binding provider obligation."
    },
    {
      "row_id": "US-04",
      "review_decision": "accepted",
      "jurisdiction": "US",
      "instrument": "CAISI_OVERVIEW",
      "source_locator": "overview concerning voluntary agreements and unclassified evaluations",
      "record_type": "institutional_program",
      "actor_type": "ai_lifecycle_organization",
      "actor_term_local": "private-sector artificial intelligence developer or evaluator",
      "conduct_type": "evaluation_participation",
      "conduct_term_local": "participate in voluntary agreements and unclassified evaluations with CAISI",
      "legal_force": "voluntary",
      "compliance_function": "evaluation_collaboration",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "not_applicable",
      "responsible_authority": "NIST",
      "implementation_body": "CAISI",
      "scope": [
        "cross_sector"
      ],
      "target_system": "artificial_intelligence_model_or_system",
      "headline_relevance": "voluntary_evaluation_infrastructure",
      "interpretation_note": "CAISI provides federal evaluation infrastructure, but private participation is voluntary rather than a market-wide legal duty."
    },
    {
      "row_id": "US-05",
      "review_decision": "accepted",
      "jurisdiction": "US",
      "instrument": "CAISI_GUIDELINES_PAGE",
      "source_locator": "voluntary guidelines and draft benchmark-evaluation practices",
      "record_type": "source_bundle",
      "derived_claims": [
        {
          "claim_id": "US-05A",
          "instrument": "CAISI_EVALUATION_GUIDELINES",
          "record_type": "guidance",
          "actor_type": "ai_lifecycle_organization",
          "actor_term_local": "advanced AI model, system or agent developer or evaluator",
          "conduct_type": "model_evaluation",
          "conduct_term_local": "use voluntary guidelines and best practices for automated AI evaluations",
          "evaluation_method": [
            "automated_evaluation",
            "benchmark_evaluation"
          ],
          "legal_force": "voluntary",
          "compliance_function": "evaluation_guidance",
          "adoption_status": "adopted",
          "applicability_status": "applicable",
          "enforcement_status": "not_applicable",
          "responsible_authority": "NIST",
          "implementation_body": "CAISI",
          "scope": [
            "cross_sector"
          ],
          "target_system": "advanced_ai_model_system_or_agent",
          "headline_relevance": "voluntary_evaluation_support"
        },
        {
          "claim_id": "US-05B",
          "instrument": "CAISI_DRAFT_BENCHMARK_PRACTICES",
          "record_type": "proposed_guidance",
          "actor_type": "ai_lifecycle_organization",
          "actor_term_local": "advanced AI model, system or agent developer or evaluator",
          "conduct_type": "model_evaluation",
          "conduct_term_local": "use proposed best practices for automated benchmark evaluations",
          "evaluation_method": [
            "automated_evaluation",
            "benchmark_evaluation"
          ],
          "legal_force": "voluntary",
          "compliance_function": "evaluation_guidance",
          "adoption_status": "proposed",
          "applicability_status": "draft_available",
          "enforcement_status": "not_applicable",
          "responsible_authority": "NIST",
          "implementation_body": "CAISI",
          "scope": [
            "cross_sector"
          ],
          "target_system": "advanced_ai_model_system_or_agent",
          "headline_relevance": "proposed_voluntary_evaluation_support"
        }
      ],
      "interpretation_note": "Both claims concern model evaluation, but neither creates a binding market-wide provider obligation."
    },
    {
      "row_id": "US-06",
      "review_decision": "accepted",
      "jurisdiction": "US",
      "instrument": "WHITE_HOUSE_AI_EXECUTIVE_POLICY",
      "source_locator": "January 2025 White House fact sheet",
      "record_type": "executive_direction",
      "actor_type": "federal_agency",
      "actor_term_local": "executive department or agency",
      "indirectly_affected_actor_type": "market_provider",
      "conduct_type": "administrative_policy_revision",
      "conduct_term_local": "review, revise or rescind agency actions inconsistent with federal artificial-intelligence leadership policy",
      "legal_force": "binding",
      "binding_scope": "executive_branch_only",
      "compliance_function": "agency_policy_direction",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "internal_executive_implementation",
      "responsible_authority": "White House",
      "implementation_body": "executive_agencies",
      "scope": [
        "government_policy"
      ],
      "headline_relevance": "deregulatory_context_only",
      "interpretation_note": "The direction binds executive agencies, not private providers."
    },
    {
      "row_id": "US-07",
      "review_decision": "accepted",
      "jurisdiction": "US",
      "instrument": "OMB_M_25_21",
      "source_locator": "scope statement",
      "record_type": "scope_rule",
      "actor_type": "federal_agency",
      "actor_term_local": "federal agency",
      "covered_scope": [
        "government_use"
      ],
      "excluded_direct_actor_types": [
        "market_provider",
        "government_vendor",
        "public"
      ],
      "legal_force": "binding",
      "binding_scope": "federal_agencies_only",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "internal_government_implementation",
      "responsible_authority": "OMB",
      "target_system": "agency_used_ai_system",
      "headline_relevance": "excludes_general_provider_duty",
      "interpretation_note": "M-25-21 binds agencies in their use of AI and must not be generalized into market-wide duties for private providers."
    },
    {
      "row_id": "US-08",
      "review_decision": "accepted",
      "jurisdiction": "US",
      "instrument": "OMB_M_25_21",
      "source_locator": "high-impact AI requirements",
      "record_type": "source_bundle",
      "derived_claims": [
        {
          "claim_id": "US-08A",
          "record_type": "obligation",
          "actor_type": "federal_agency",
          "actor_term_local": "federal agency using high-impact AI",
          "conduct_type": "pre_deployment_testing",
          "conduct_family": "evaluation",
          "conduct_term_local": "conduct pre-deployment testing of high-impact AI",
          "legal_force": "binding",
          "binding_scope": "federal_agencies_only",
          "compliance_function": "direct_obligation",
          "adoption_status": "adopted",
          "applicability_status": "applicable",
          "enforcement_status": "internal_government_implementation",
          "responsible_authority": "OMB",
          "implementation_body": "federal_agencies",
          "scope": [
            "government_use"
          ],
          "target_system": "high_impact_ai_system",
          "noncompliance_consequence": "discontinue_ai_use",
          "headline_relevance": "government_only_binding"
        },
        {
          "claim_id": "US-08B",
          "record_type": "obligation",
          "actor_type": "federal_agency",
          "actor_term_local": "federal agency using high-impact AI",
          "conduct_type": "risk_assessment",
          "conduct_term_local": "complete an AI impact assessment for high-impact AI",
          "legal_force": "binding",
          "binding_scope": "federal_agencies_only",
          "compliance_function": "direct_obligation",
          "adoption_status": "adopted",
          "applicability_status": "applicable",
          "enforcement_status": "internal_government_implementation",
          "responsible_authority": "OMB",
          "implementation_body": "federal_agencies",
          "scope": [
            "government_use"
          ],
          "target_system": "high_impact_ai_system",
          "noncompliance_consequence": "discontinue_ai_use",
          "headline_relevance": "government_only_support"
        }
      ],
      "interpretation_note": "These are binding government-use controls, not general market-provider obligations."
    },
    {
      "row_id": "US-09",
      "review_decision": "accepted",
      "jurisdiction": "US",
      "instrument": "OMB_M_25_22",
      "source_locator": "testing and evaluation in procurement",
      "record_type": "source_bundle",
      "derived_claims": [
        {
          "claim_id": "US-09A",
          "record_type": "obligation",
          "actor_type": "federal_agency",
          "actor_term_local": "federal agency procuring AI",
          "conduct_type": "procurement_testing",
          "conduct_family": "evaluation",
          "conduct_term_local": "test proposed artificial-intelligence solutions during the procurement process",
          "legal_force": "binding",
          "binding_scope": "federal_agencies_only",
          "compliance_function": "direct_obligation",
          "adoption_status": "adopted",
          "applicability_status": "applicable",
          "enforcement_status": "internal_government_implementation",
          "responsible_authority": "OMB",
          "implementation_body": "procuring_agencies",
          "scope": [
            "government_procurement"
          ],
          "target_system": "proposed_ai_solution",
          "headline_relevance": "government_procurement_only"
        },
        {
          "claim_id": "US-09B",
          "record_type": "procurement_requirement",
          "actor_type": "federal_agency",
          "actor_term_local": "federal agency procuring AI",
          "conduct_type": "contract_terms_requirement",
          "conduct_term_local": "require ongoing testing and monitoring through the procurement contract",
          "required_vendor_conduct": [
            "ongoing_testing",
            "performance_monitoring"
          ],
          "legal_force": "binding",
          "binding_scope": "federal_agencies_only",
          "compliance_function": "contract_condition_creation",
          "adoption_status": "adopted",
          "applicability_status": "applicable",
          "enforcement_status": "internal_government_implementation",
          "responsible_authority": "OMB",
          "implementation_body": "procuring_agencies",
          "scope": [
            "government_procurement"
          ],
          "headline_relevance": "government_procurement_only"
        },
        {
          "claim_id": "US-09C",
          "record_type": "contract_mediated_obligation",
          "actor_type": "government_vendor",
          "actor_term_local": "AI vendor performing a federal contract",
          "conduct_type": "evaluation_access",
          "conduct_term_local": "preserve access necessary for independent evaluation of the contracted artificial-intelligence system",
          "legal_force": "contractual",
          "binding_scope": "government_contract_only",
          "compliance_function": "procurement_contract_obligation",
          "adoption_status": "adopted",
          "applicability_status": "contingent_on_contract",
          "enforcement_status": "contractual_enforcement",
          "responsible_authority": "procuring_agency",
          "policy_authority": "OMB",
          "scope": [
            "government_procurement"
          ],
          "target_system": "contracted_ai_system",
          "headline_relevance": "government_procurement_only"
        }
      ],
      "interpretation_note": "Agency duties arise directly from the memorandum, while vendor duties arise through government contracts."
    },
    {
      "row_id": "US-10",
      "review_decision": "accepted",
      "jurisdiction": "US",
      "instrument": "OMB_M_25_22",
      "source_locator": "disclosure and performance monitoring for contracted AI use",
      "record_type": "source_bundle",
      "derived_claims": [
        {
          "claim_id": "US-10A",
          "record_type": "contract_mediated_obligation",
          "actor_type": "government_vendor",
          "actor_term_local": "federal vendor performing an AI-related government contract",
          "conduct_type": "contract_documentation",
          "conduct_term_local": "provide documentation required for government oversight of the contracted AI system",
          "legal_force": "contractual",
          "binding_scope": "government_contract_only",
          "compliance_function": "procurement_contract_obligation",
          "adoption_status": "adopted",
          "applicability_status": "contingent_on_contract",
          "enforcement_status": "contractual_enforcement",
          "responsible_authority": "procuring_agency",
          "policy_authority": "OMB",
          "scope": [
            "government_procurement"
          ],
          "target_system": "contracted_ai_system",
          "headline_relevance": "government_procurement_only"
        },
        {
          "claim_id": "US-10B",
          "record_type": "contract_mediated_obligation",
          "actor_type": "government_vendor",
          "actor_term_local": "federal vendor performing an AI-related government contract",
          "conduct_type": "monitoring_support",
          "conduct_term_local": "support monitoring and enable performance-based oversight of the contracted AI system",
          "legal_force": "contractual",
          "binding_scope": "government_contract_only",
          "compliance_function": "procurement_contract_obligation",
          "adoption_status": "adopted",
          "applicability_status": "contingent_on_contract",
          "enforcement_status": "contractual_enforcement",
          "responsible_authority": "procuring_agency",
          "policy_authority": "OMB",
          "scope": [
            "government_procurement"
          ],
          "target_system": "contracted_ai_system",
          "headline_relevance": "government_procurement_only"
        }
      ],
      "interpretation_note": "These duties are limited to the government-contract relationship and do not apply to providers generally."
    },
    {
      "row_id": "US-11",
      "review_decision": "accepted",
      "jurisdiction": "US",
      "instrument": "WHITE_HOUSE_AI_FRAMEWORK_FACT_SHEET",
      "source_locator": "December 2025 fact sheet",
      "record_type": "proposed_policy",
      "current_actor_type": "federal_agency",
      "current_actor_term_local": "FTC or FCC",
      "prospective_actor_type": "market_provider",
      "prospective_actor_term_local": "AI model company",
      "conduct_type": "reporting_and_disclosure",
      "conduct_term_local": "comply with a possible future federal reporting and disclosure standard for AI models",
      "proposal_action": "consider adopting a federal reporting and disclosure standard for AI models",
      "legal_force": "proposed",
      "compliance_function": "prospective_regulatory_requirement",
      "adoption_status": "proposed",
      "applicability_status": "not_yet_applicable",
      "enforcement_status": "not_applicable",
      "policy_origin": "White House",
      "potential_responsible_authorities": [
        "FTC",
        "FCC"
      ],
      "scope": [
        "cross_sector"
      ],
      "target_system": "artificial_intelligence_model",
      "headline_relevance": "proposed_only",
      "interpretation_note": "The fact sheet describes possible future regulation. It does not create a currently applicable model-evaluation duty."
    },
    {
      "row_id": "US-12",
      "review_decision": "accepted",
      "jurisdiction": "US",
      "instrument": "WHITE_HOUSE_AI_POLICY_ACTION_MATERIALS",
      "source_locator": "AI Action Plan and later White House policy-action materials",
      "record_type": "policy_context",
      "actor_type": "federal_agency",
      "actor_term_local": "federal agency",
      "additional_affected_actor_type": "ecosystem_stakeholder",
      "additional_actor_term_local": "stakeholder participating in the United States artificial-intelligence ecosystem",
      "conduct_type": "evaluation_infrastructure_coordination",
      "conduct_term_local": "advance standards, evaluation tools, procurement practices and security coordination",
      "source_topics": [
        "innovation",
        "infrastructure",
        "standards",
        "evaluation_tools",
        "procurement",
        "security_coordination"
      ],
      "legal_force": "mixed",
      "compliance_function": "policy_direction",
      "adoption_status": "adopted",
      "applicability_status": "applicable",
      "enforcement_status": "not_determinable_from_passage",
      "responsible_authorities": [
        "White House",
        "NIST",
        "CAISI"
      ],
      "scope": [
        "government_policy",
        "cross_sector_support"
      ],
      "headline_relevance": "contextual_only",
      "interpretation_note": "Current policy supports standards, evaluation tools and coordination but does not itself impose a binding model-evaluation obligation on private market providers."
    }
  ],
  "headline_judgments": {
    "EU": {
      "market_provider": "binding_applicable_for_defined_class",
      "defined_class": "provider of a general-purpose AI model with systemic risk",
      "decisive_evidence": [
        "EU-06"
      ],
      "supporting_evidence": [
        "EU-01",
        "EU-02",
        "EU-07",
        "EU-10B",
        "EU-11A"
      ],
      "qualification": "EU-11B preserves a transition period for qualifying existing models."
    },
    "US": {
      "market_provider_cross_sector": "no_current_binding_model_evaluation_requirement",
      "federal_agency_government_use": "binding_testing_and_impact_assessment_requirements",
      "government_procurement": "binding_agency_controls_and_contract_mediated_vendor_duties",
      "voluntary_cross_sector": "active_evaluation_guidance_and_infrastructure",
      "proposed_future": "reporting_and_disclosure_standard_only"
    }
  },
  "validation_expectations": {
    "parent_row_count": 24,
    "eu_parent_row_count": 12,
    "us_parent_row_count": 12,
    "normalized_claim_count": 32,
    "pending_review_count": 0,
    "rejected_review_count": 0
  }
};
