// GENERATED by scripts/embed-provenance.ts — do not edit.
//
// What the repository actually declares about itself, captured at build time.
// An `undefined` field means the repository does not declare it; the memo
// renderer says so rather than substituting a plausible value.

export interface LicenseRecord {
  /** Repo-relative path of the licence file this came from. */
  readonly file: string;
  /** Identifier only when the file names one. Undefined means unrecognised. */
  readonly identifier?: string;
}

export interface RepoProvenance {
  readonly repository?: string;
  readonly commit?: string;
  readonly softwareLicense?: LicenseRecord;
  readonly dataLicense?: LicenseRecord;
  readonly copyright?: string;
}

export const REPO_PROVENANCE: RepoProvenance = {
  "repository": "https://github.com/saykig/Writ",
  "commit": "57abc95a714ddc3c1112a4a2e52e7a6c78e797ef",
  "softwareLicense": {
    "file": "LICENSE",
    "identifier": "Apache-2.0"
  },
  "copyright": "Copyright 2026 Sara Kim"
};
