/**
 * Generate `src/schemas.embedded.ts` — the vendored JSON Schemas inlined as text
 * so consumers can load them without a runtime filesystem read.
 *
 * Why: bundlers (Next/webpack) rewrite `import.meta.url` to a build-time absolute
 * path, so the `readFileSync` path resolution in `schemas.ts` breaks inside a
 * serverless bundle (the schema files are not shipped at that baked path). Inlining
 * the schema text removes the file dependency entirely. The data is frozen, and
 * `prebuild` regenerates this file so it can never drift from `schemas/`.
 *
 * Run: `bun scripts/embed-schemas.ts` (wired as the domain package `prebuild`).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { SCHEMA_KINDS, SCHEMA_FILES } from "../src/schemas.js";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = join(here, "..", "schemas");
const outFile = join(here, "..", "src", "schemas.embedded.ts");

const entries = SCHEMA_KINDS.map((kind) => {
  const text = readFileSync(join(schemasDir, SCHEMA_FILES[kind]), "utf8");
  return `  ${JSON.stringify(kind)}: ${JSON.stringify(text)},`;
}).join("\n");

const body = `// AUTO-GENERATED by scripts/embed-schemas.ts — do not edit by hand.
// The vendored JSON Schemas, inlined as text so they load without a filesystem
// read (safe inside bundled/serverless runtimes). Regenerated by \`prebuild\`.
import type { SchemaKind } from "./schemas.js";

export const EMBEDDED_SCHEMA_TEXT: Readonly<Record<SchemaKind, string>> = Object.freeze({
${entries}
});
`;

writeFileSync(outFile, body);
console.log(`embed-schemas: wrote ${outFile} (${SCHEMA_KINDS.length} schemas)`);
