/**
 * Generate `src/schemas.embedded.ts` — the vendored JSON Schemas inlined as text
 * so consumers can load them without a runtime filesystem read.
 *
 * Why: bundlers (Next/webpack) rewrite `import.meta.url` to a build-time absolute
 * path, so the `readFileSync` path resolution in `schemas.ts` breaks inside a
 * serverless bundle (the schema files are not shipped at that baked path). Inlining
 * the schema text removes the file dependency entirely. The data is frozen, and
 * `prebuild` regenerates this file so it cannot drift from the vendored schema directory.
 *
 * Run: `bun scripts/embed-schemas.ts` (wired as the domain package `prebuild`).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
const SCHEMA_FILES = {
  evidence: "evidence.schema.json",
  "source-registry": "source-registry.schema.json",
  record: "record.schema.json",
  "corpus-manifest": "corpus-manifest.schema.json",
  "corpus-catalog": "corpus-catalog.schema.json",
  "record-link": "record-link.schema.json",
  "legal-policy-record": "legal-policy-record.schema.json",
  "institutional-record": "institutional-record.schema.json",
  "record-judgment": "record-judgment.schema.json",
} as const;
const SCHEMA_KINDS = Object.keys(SCHEMA_FILES) as Array<keyof typeof SCHEMA_FILES>;
const COMPATIBILITY_SCHEMA_FILES = {
  record: "compatibility/record-grammar-v0.1/record.schema.json",
  "legal-policy-record": "compatibility/record-grammar-v0.1/legal-policy-record.schema.json",
  "institutional-record": "compatibility/record-grammar-v0.1/institutional-record.schema.json",
  "record-judgment": "compatibility/record-grammar-v0.1/record-judgment.schema.json",
} as const;
const COMPATIBILITY_SCHEMA_KINDS = Object.keys(COMPATIBILITY_SCHEMA_FILES) as Array<
  keyof typeof COMPATIBILITY_SCHEMA_FILES
>;
const CORPUS_COMPATIBILITY_CONTRACT_FILES = {
  "eu-us-ai-reviewed-document":
    "compatibility/eu-us-ai-reviewed-v1/reviewed-corpus-document.schema.json",
} as const;
const CORPUS_COMPATIBILITY_CONTRACT_KINDS = Object.keys(
  CORPUS_COMPATIBILITY_CONTRACT_FILES,
) as Array<keyof typeof CORPUS_COMPATIBILITY_CONTRACT_FILES>;

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = join(here, "..", "schemas");
const outFile = join(here, "..", "src", "schemas.embedded.ts");

const entries = SCHEMA_KINDS.map((kind) => {
  const text = readFileSync(join(schemasDir, SCHEMA_FILES[kind]), "utf8");
  return `  ${JSON.stringify(kind)}: ${JSON.stringify(text)},`;
}).join("\n");

const compatibilityEntries = COMPATIBILITY_SCHEMA_KINDS.map((kind) => {
  const text = readFileSync(join(schemasDir, COMPATIBILITY_SCHEMA_FILES[kind]), "utf8");
  return `  ${JSON.stringify(kind)}: ${JSON.stringify(text)},`;
}).join("\n");

const corpusContractEntries = CORPUS_COMPATIBILITY_CONTRACT_KINDS.map((kind) => {
  const text = readFileSync(join(schemasDir, CORPUS_COMPATIBILITY_CONTRACT_FILES[kind]), "utf8");
  return `  ${JSON.stringify(kind)}: ${JSON.stringify(text)},`;
}).join("\n");

const reviewArtifactJudgmentText = readFileSync(
  join(schemasDir, "record-judgment-v0.3.schema.json"),
  "utf8",
);

const body = `// AUTO-GENERATED by scripts/embed-schemas.ts — do not edit by hand.
// The vendored JSON Schemas, inlined as text so they load without a filesystem
// read (safe inside bundled/serverless runtimes). Regenerated by \`prebuild\`.
import type {
  CompatibilitySchemaKind,
  CorpusCompatibilityContractKind,
  SchemaKind,
} from "./schemas.js";

export const EMBEDDED_SCHEMA_TEXT: Readonly<Record<SchemaKind, string>> = Object.freeze({
${entries}
});

export const EMBEDDED_COMPATIBILITY_SCHEMA_TEXT: Readonly<
  Record<CompatibilitySchemaKind, string>
> = Object.freeze({
${compatibilityEntries}
});

export const EMBEDDED_CORPUS_COMPATIBILITY_CONTRACT_TEXT: Readonly<
  Record<CorpusCompatibilityContractKind, string>
> = Object.freeze({
${corpusContractEntries}
});

export const EMBEDDED_REVIEW_ARTIFACT_JUDGMENT_SCHEMA_TEXT = ${JSON.stringify(reviewArtifactJudgmentText)};
`;

writeFileSync(outFile, body);
console.log(
  `embed-schemas: wrote ${outFile} (${SCHEMA_KINDS.length} current schemas, ` +
    `${COMPATIBILITY_SCHEMA_KINDS.length} compatibility schemas, ` +
    `${CORPUS_COMPATIBILITY_CONTRACT_KINDS.length} corpus compatibility contracts)`,
);
