import { sha256Canonical } from "@writ/provenance";
import { need, validateSnapshot, type Snapshot } from "./contract.js";
export interface NativeAttachment {
  archive_base64: string;
  archive_sha256: string;
  inspection: unknown;
  replay: unknown;
}
const escapeHtml = (s: string) =>
  s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
export function renderView(snapshot: Snapshot, native: NativeAttachment): string {
  validateSnapshot(snapshot);
  // Static summaries are authored for this frozen edition, never for arbitrary packets.
  const packetIdentities = [
    "sha256:4b196ed748bdaf9d7dfa271ee55287c7b56bc6eb8c85f2036f60acd5b149f636",
    "sha256:23ac0d7642ebe3854d40ba291b360644f5a79cd2c91ddaed6554542f4bcf8a2a",
    "sha256:7e87afb0ad73efe05cbed4ffddcae3e35da0725968e2f1496ffb5a74b64fdeee",
  ];
  need(
    sha256Canonical(snapshot.packets) === packetIdentities[snapshot.packets.length - 1],
    "UNSUPPORTED_DISPLAY_EDITION",
  );
  const data = JSON.stringify({ snapshot, native, identity: sha256Canonical(snapshot) }).replaceAll(
    "<",
    "\\u003c",
  );
  return String.raw`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OPERA · Revisable assessment</title>
<style>
:root{color-scheme:light;--paper:#f8f6f0;--ink:#222a30;--muted:#535d63;--line:#c8cec9;--blue:#164e70;--amber:#754900}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.6 Georgia,serif}header,main,footer{max-width:1200px;margin:auto;padding:28px 40px}header{border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:baseline;gap:20px}.brand,nav,button,label,select,.meta,.status,summary,footer{font-family:system-ui,sans-serif}.brand{font-weight:650;color:var(--blue)}.meta,footer{font-size:13px;color:var(--muted)}h1{font-size:clamp(30px,4vw,48px);line-height:1.15;font-weight:400;max-width:22ch;margin:18px 0}h2{font-size:26px;font-weight:400;line-height:1.25;margin:32px 0 12px}h3{font-size:20px;margin:20px 0 8px}p{max-width:72ch;margin:8px 0 18px}.intro{max-width:76ch;margin-bottom:26px}nav{display:flex;gap:8px;flex-wrap:wrap;border-bottom:1px solid var(--line);padding-bottom:18px}button,select,textarea{font:inherit}button{cursor:pointer;font:14px/1.3 system-ui,sans-serif;border:1px solid var(--line);border-radius:5px;padding:11px 15px;color:var(--ink);background:#fff}button:hover{border-color:var(--blue);background:#edf3f4}button[aria-current=true],button.primary{background:var(--blue);color:white;border-color:var(--blue)}button:disabled{opacity:.55;cursor:default}a{color:var(--blue);text-underline-offset:3px}:focus-visible{outline:3px solid #a46300;outline-offset:3px}.columns{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:48px}.row{border-top:1px solid var(--line);padding:14px 0}.row h3{margin:0 0 8px}.status{display:inline-block;font-size:13px;color:var(--amber);font-weight:650}.record-id{font:12px system-ui,sans-serif;color:var(--muted)}details{border-top:1px solid var(--line);padding:12px 0}summary{cursor:pointer;font-size:15px;color:var(--blue)}blockquote{margin:14px 0;padding:0 16px;border-left:1px solid var(--line)}label{display:block;font-size:14px;font-weight:600;margin:18px 0 6px}select,textarea{width:100%;padding:10px;border:1px solid #7c898c;border-radius:4px;background:#fff;color:var(--ink);font:15px system-ui,sans-serif}textarea{min-height:120px;resize:vertical}.aside{padding-top:8px}code{font-size:12px;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;max-height:350px;overflow:auto;background:#efeee8;padding:12px}#message{font:14px system-ui,sans-serif;min-height:36px;margin-top:12px}footer{border-top:1px solid var(--line);margin-top:40px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.history-event{background:#eeeee5;padding:12px}.sr{position:absolute;width:1px;height:1px;padding:0;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:780px){header,main,footer{padding:20px}.columns{grid-template-columns:1fr;gap:12px}header{align-items:start}.meta{max-width:28ch}h1{font-size:34px}.aside{border-top:1px solid var(--line);margin-top:24px}}
</style>
<header><span class="brand">Writ / Assessment notebook</span><span class="meta">Local research pilot · OPERA 2011–2012</span></header>
<main><div class="intro"><span class="status">Experimental analyst assessment</span><h1>What survives a changed measurement?</h1><p>${escapeHtml(snapshot.packets[0]!.question)}</p><p class="meta">Three selected dated sections from CERN. Source reports, analyst positions and current use remain distinct.</p></div>
<nav aria-label="Assessment history" id="stages"></nav><div class="columns"><article><h2 id="stage-title"></h2><p id="current"></p><section aria-labelledby="explanation-heading"><h2 id="explanation-heading">Working explanations</h2><div id="explanations"></div></section><section><h2>Why this assessment changed</h2><div id="changes"></div></section><section><h2>Assumption and disagreement</h2><div id="disagreement"></div></section><section><h2>Evidence in this stage</h2><div id="sources"></div></section><section><h2>Still unresolved</h2><div id="questions"></div></section></article>
<aside class="aside"><h2>Author a continuation</h2><p class="meta">Record your position on calibration sufficiency (A1). The original records stay intact. Export a proposal for separate checking.</p><form id="revision"><label for="position">Your current use of A1</label><select id="position"><option value="contested">Contested</option><option value="withdrawn">Withdrawn</option><option value="retained">Retained as an explicit assumption</option></select><label for="rationale">Reason for this revision</label><textarea id="rationale" required maxlength="12000" placeholder="Explain the source or assumption behind your change."></textarea><button class="primary" type="submit">Generate continuation request</button><label for="request-text">Generated request · save as continuation-request.json</label><textarea id="request-text" readonly placeholder="Your generated JSON will appear here. It stays visible even if a download is unavailable."></textarea><div class="actions"><button type="button" id="save-request" disabled>Save request file</button><button type="button" id="select-request" disabled>Select request text</button></div><p id="message" role="status" aria-live="polite">Request generator has not started. If this message remains, use the documented CLI workflow.</p></form><p class="meta">Authoring applies to the complete loaded history. Selected historical stages are for inspection.</p><h3>Authored history</h3><div id="events"></div><details><summary>Inspect assessment identity</summary><code id="identity"></code><div class="actions"><button id="download-history">Export assessment history</button></div></details><details><summary>Native shared-analysis exercise</summary><p class="meta">Separate synthetic alpha/beta decision cases. Retained replay checked two original candidates and two revision impacts. No OPERA mathematical result is implied. Successor checks remain absent in this exercise.</p><code id="native-identity"></code><div class="actions"><button id="download-native">Export native archive</button></div><pre id="native-records"></pre></details></aside></div></main>
<footer>Authored proposals require substantive review. Exact identity and history checks establish neither physics, human acceptance nor authority to act. No network connection is required to use this notebook.</footer>
<script type="application/json" id="data">${data}</script><script>
const data=JSON.parse(document.getElementById('data').textContent);let stage=data.snapshot.packets.length-1;
const el=id=>document.getElementById(id);const node=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;};
const all=data.snapshot.packets.flatMap(p=>p.records);const titles=['Initial report · Sep 2011','Possible timing faults · Feb 2012','Measurement correction · Jun 2012'];
const summaries=['The reported anomaly merits investigation. None of the three explanations is established. Excluding a timing fault depends on the disputed assumption A1.','Two possible timing effects require further testing. Alpha has withdrawn A1; its conditional exclusion of a timing fault needs reassessment.','The source attributes the original anomaly to a fibre timing fault. That changes the current interpretation while preserving the original report.'];
const states=[['Unestablished','Open under dispute','Open'],['Unestablished','Specific candidates; unquantified','Open'],['Not supported by this anomaly','Source-attributed explanation','Not established by the supplied material']];
function show(){el('stages').replaceChildren();data.snapshot.packets.forEach((p,i)=>{const b=node('button',titles[i]);b.setAttribute('aria-current',String(i===stage));b.onclick=()=>{stage=i;show();};el('stages').append(b);});el('stage-title').textContent=titles[stage];el('current').textContent=summaries[stage];
 const records=data.snapshot.packets.filter(p=>p.stage<=stage).flatMap(p=>p.records);el('explanations').replaceChildren();records.filter(r=>r.kind==='hypothesis').forEach((r,i)=>{const d=node('div','','row');d.append(node('span',r.id,'record-id'),node('h3',r.title),node('span',states[stage][i],'status'),node('p',r.text));el('explanations').append(d);});
 const sections={changes:['source_update','source_correction'],disagreement:['assumption','disagreement','interpretation'],questions:['question']};for(const [id,kinds]of Object.entries(sections)){el(id).replaceChildren();const selected=records.filter(r=>kinds.includes(r.kind));if(!selected.length)el(id).append(node('p','Initial edition. No update has been supplied.','meta'));selected.forEach(r=>{const d=node('div','','row');d.append(node('span',r.id,'record-id'),node('h3',r.title),node('p',r.text));if(r.depends_on.length)d.append(node('p','Declared dependencies: '+r.depends_on.join(', '),'meta'));el(id).append(d);});}
 el('sources').replaceChildren();records.filter(r=>r.kind==='source').forEach(r=>{const d=document.createElement('details');d.append(node('summary',r.id+' · CERN · '+r.date),node('p',r.text),node('blockquote',r.excerpt));const a=node('a','Read the publisher page');a.href=r.url;a.target='_blank';a.rel='noopener noreferrer';d.append(a,node('p',r.capture,'meta'),node('code',r.excerpt_sha256),node('p','Parent byte span: '+r.parent_byte_span.join('–')+'. Selected excerpt only.','meta'));el('sources').append(d);});}
function download(name,bytes,type='application/json'){let url;let a;try{url=URL.createObjectURL(new Blob([bytes],{type}));a=document.createElement('a');a.href=url;a.download=name;a.hidden=true;document.body.append(a);a.click();el('message').textContent='Save requested for '+name+'. Check your browser downloads; the page cannot confirm that a file was saved. Generated request text remains available below.';}catch(error){el('message').textContent='The browser could not start a download. Select the generated request text and save it as a plain-text JSON file instead.';}finally{if(a)a.remove();if(url)setTimeout(()=>URL.revokeObjectURL(url),1000);}}
el('revision').onsubmit=e=>{e.preventDefault();const rationale=el('rationale').value.trim();if(!rationale){el('message').textContent='Add a reason before exporting your request.';el('rationale').focus();return;}const request={schema:'writ.experimental-continuation-request.v1',assessment_id:data.snapshot.packets[0].assessment_id,base_sha256:data.identity,target:'A1',status:el('position').value,rationale,source_ids:all.filter(r=>r.kind==='source').map(r=>r.id)};el('request-text').value=JSON.stringify(request,null,2)+'\n';el('save-request').disabled=false;el('select-request').disabled=false;el('message').textContent='Request generated below. Save the file, or select and copy its text into a plain-text file named continuation-request.json. Separate receiving is still required.';};
el('save-request').onclick=()=>download('continuation-request.json',el('request-text').value);el('select-request').onclick=()=>{el('request-text').focus();el('request-text').select();el('message').textContent='Request text selected. Copy it and save as plain-text JSON; selection alone does not save a file.';};el('message').textContent='Ready. Enter a reason, then generate the request to inspect its exact contents.';
el('identity').textContent=data.identity;el('native-identity').textContent=data.native.archive_sha256;el('native-records').textContent=JSON.stringify({inspection:data.native.inspection,retained_replay:data.native.replay},null,2);
el('download-history').onclick=()=>download('assessment-history.json',JSON.stringify(data.snapshot,null,2)+'\n');el('download-native').onclick=()=>download('shared-analysis.archive.json',Uint8Array.from(atob(data.native.archive_base64),c=>c.charCodeAt(0)));
el('events').replaceChildren();if(!data.snapshot.events.length)el('events').append(node('p','No authored continuation has been appended.','meta'));data.snapshot.events.forEach((r,i)=>{const d=node('div','','history-event');d.append(node('strong','Revision '+(i+1)+' · '+r.status),node('p',r.rationale));el('events').append(d);});show();
</script></html>`;
}
